Add GatheringICECandidate Finish Duration to Meeting Event
aws/amazon-chime-sdk-js pull request #1023
Opened 2021-01-22 01:46 UTC by RidipDe

**Issue #:**

**Description of changes:**
Add GatheringICECandidate Finish Duration to Meeting Event and to Demo App

**Testing**

1. Have you successfully run `npm run build:release` locally?
Yes

2. How did you test these changes?
Manually

3. Can these changes be tested using the demo application? If yes, which demo application can be used to test it?
Yes, meeting app

4. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?
Yes

5. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?
No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-26 02:02 UTC, simmkyu requested changes
- Please add a description to the guide.
https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/06_Meeting_Events.md#meeting-attributes
- Suggest renaming it to `iceGatheringDurationMs`
- Ignore this metric library in the [serverless .gitignore file](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/.gitignore). Otherwise, these files show up as untracked in a local Git repo.
  ```
  src/aws-embedded-metrics
  ```

2021-01-27 22:04 UTC, RidipDe commented on src/audiovideocontroller/AudioVideoControllerState.ts
> +  gatheringICECandidateFinishDurationMs: number | null = null;
Changed gatheringICECandidateFinishDurationMs -> iceGatheringDurationMs

2021-01-27 22:05 UTC, RidipDe commented on demos/serverless/src/handlers.js
> +  const metricList = ['signalingOpenDurationMs', 'gatheringICECandidateFinishDurationMs'];
CW Metrics treats null as 0. So no changes required.

2021-01-28 01:15 UTC, simmkyu requested changes

2021-01-28 01:15 UTC, simmkyu commented on guides/06_Meeting_Events.md
> +|`iceGatheringDurationMs`|The time taken for connetion's ICE gathering state to complete.<br><br>Unit: Milliseconds|`meetingStartSucceeded`, `meetingStartFailed`, `meetingEnded`, `meetingFailed`
Typo: `connetion` => `connection`

2021-01-28 01:15 UTC, simmkyu commented on src/task/FinishGatheringICECandidatesTask.ts
> +      this.context.iceGatheringDurationMs = Math.round(Date.now() - this.startTimestampMs);
If the task returns at line 71 or 92 or throws anywhere before `this.startTimestampMs` is set, the `iceGatheringDurationMs` value might be `NaN`. You can solve in this way:

1. Use the try/catch statement to wrap only the promise.
2. To be defensive, also check if the `startTimestampMs` exists.

```
try {
  await new Promise<void>((resolve, reject) => {
     ...
  });
} catch (error) {
  throw error;
} finally {
  if (this.startTimestampMs) {
     this.context.iceGatheringDurationMs  = Math.round(Date.now() - this.startTimestampMs);
  }
}
```

2021-01-28 23:57 UTC, simmkyu approved these changes

2021-01-29 01:13 UTC, simmkyu approved these changes

2021-01-29 03:54 UTC, merged