Fix crash issue "Cannot read property 'toLowerCasePropertyNames' of undefined"
aws/amazon-chime-sdk-js pull request #1072
Opened 2021-02-17 10:21 UTC by narek-king

Related issue link: https://github.com/aws/amazon-chime-sdk-js/issues/1052

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-17 18:04 UTC, ltrung commented
@narek-king Thank for fixing this. Do you mind updating the unit test for the case that causes the crash here https://github.com/aws/amazon-chime-sdk-js/blob/master/test/meetingsession/MeetingSessionConfiguration.test.ts ?

2021-02-19 08:44 UTC, narek-king commented
@ltrung I fixed the unit tests. The CI fails and I am not sure why. Can you please review it?

2021-02-19 21:36 UTC, ltrung commented
> @ltrung I fixed the unit tests. The CI fails and I am not sure why. Can you please review it?

@narek-king  currently forked PR would not be able to trigger our integration test as it cannot access GitHub secret. We are working on fixing it.
Regarding your PR, could you clarify what the issue is? I could run the unit test you added successfully without the fix. [].map should not cause any issue.

2021-02-20 10:19 UTC, narek-king commented
> > @ltrung I fixed the unit tests. The CI fails and I am not sure why. Can you please review it?
> 
> @narek-king currently forked PR would not be able to trigger our integration test as it cannot access GitHub secret. We are working on fixing it.
> Regarding your PR, could you clarify what the issue is? I could run the unit test you added successfully without the fix. [].map should not cause any issue.

@ltrung I agree that [].map should not cause any issue but I have a real case that it didn't work. This fixed my problem and I am currently using the SDK from my forked repo. In my opinion, the problem is not related to [].map but more of recursively calling the `toLowerCasePropertyName` method. In the scope, the reference of the method is not accessible. I was thinking to refactor to call as a static method but in this case, it doesn't make sense. 
I was thinking of another case where the input is [[]] but didn't have time to check.
![image](https://user-images.githubusercontent.com/14344767/108592263-7aeb8780-7386-11eb-88ef-3e8f98576864.png)
I am not sure why this is hapenning^

2021-02-20 21:58 UTC, richnew10 commented on CHANGELOG.md
> +- Fix Cannot read property 'toLowerCasePropertyNames' of undefined
This needs to move to the 'Unreleased' section.

2021-02-20 22:03 UTC, richnew10 commented on src/meetingsession/MeetingSessionConfiguration.ts
> +      }
I'm not entirely sure what you're trying to fix here, but I suspect the correct thing to do is to move `toLowerCasePropertyNames` out as a free function. Even with your change this use of `this` is incorrect.

2021-02-20 22:03 UTC, richnew10 requested changes
See inline.

2021-09-10 01:30 UTC, nainkunal933 commented
> > > @ltrung I fixed the unit tests. The CI fails and I am not sure why. Can you please review it?
> > 
> > 
> > @narek-king currently forked PR would not be able to trigger our integration test as it cannot access GitHub secret. We are working on fixing it.
> > Regarding your PR, could you clarify what the issue is? I could run the unit test you added successfully without the fix. [].map should not cause any issue.
> 
> @ltrung I agree that [].map should not cause any issue but I have a real case that it didn't work. This fixed my problem and I am currently using the SDK from my forked repo. In my opinion, the problem is not related to [].map but more of recursively calling the `toLowerCasePropertyName` method. In the scope, the reference of the method is not accessible. I was thinking to refactor to call as a static method but in this case, it doesn't make sense.
> I was thinking of another case where the input is [[]] but didn't have time to check.
> ![image](https://user-images.githubusercontent.com/14344767/108592263-7aeb8780-7386-11eb-88ef-3e8f98576864.png)
> I am not sure why this is hapenning^

Hi @narek-king, thank you for opening this PR. I have looked through your code fix. It seems like you are checking for array length before calling `return input.map(this.toLowerCasePropertyNames);`

The reason why the code is throwing undefined error here is because of `Array.map()`'s behavior. Here is quote from the methods implementation.

>“If a thisArg parameter is provided, it will be used as callback’s this value. Otherwise, the value undefined will be used as its this value. The this value ultimately observable by callbackFn is determined according to the usual rules for determining the this seen by a function.”

If I understand correctly, this is why @richnew10 is referring to the usage of `this` as incorrect in the [comment above](https://github.com/aws/amazon-chime-sdk-js/pull/1072#discussion_r579714994).

One way to fix this will be to pass `this` as a param to the map method, like this:
![Screen Shot 2021-09-09 at 12 05 25 PM](https://user-images.githubusercontent.com/31940639/132783876-c87c2e86-aaa4-4014-9c8b-7fd82901917a.png)

Please refer to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) for more info on this optional parameter.

I will be raising a PR soon to fix this by making the method static. I have updated the issue #1052 with my comment. Please let me know if you have any questions.

2021-09-10 01:40 UTC, nainkunal933 commented
> @ltrung I fixed the unit tests. The CI fails and I am not sure why. Can you please review it?

@narek-king The CI is failing because external PRs that are coming from a fork do not have access to GitHub secrets. So, you will see that the integration tests are not running. Currently, we do not have a fix for this issue and we plan to resolve this in the future.

Because the tests will not run we will not be able to merge this PR. I am sorry for this inconvenience. I want to thank you for taking the time to open this PR. Your PR was very helpful in understanding the issue. Please refer to the issue #1052 as I will keep you updated there and feel free to review my PR 😄

2021-09-10 01:40 UTC, closed without merging