Rephrase the signaling status code documentations
aws/amazon-chime-sdk-js pull request #1377
Opened 2021-06-22 17:49 UTC by simmkyu

**Issue #:**
N/A

**Description of changes:**
- Rephrase the signaling status code documentations

**Testing**

1. Have you successfully run `npm run build:release` locally? Yes
2. How did you test these changes? Check the generated HTML files
3. Can these changes be tested using the demo application? If yes, which demo application can be used to test it? No
4. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved? No
5. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved? No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-22 18:01 UTC, vidya-mohan approved these changes

2021-06-22 22:22 UTC, anuranduttaroy submitted a review, later dismissed

2021-06-23 16:04 UTC, ltrung approved these changes

2021-06-23 16:13 UTC, ltrung commented
Seem you need to edit CHANGELOG for the build to pass.

2021-06-23 16:14 UTC, ltrung requested changes
You commit package-lock.json changes which reverted back to lockfile version 1.

2021-06-23 17:51 UTC, ltrung approved these changes

2021-06-24 16:19 UTC, merged