Add some instructions for CSP setup
aws/amazon-chime-sdk-js pull request #1556
Opened 2021-08-31 00:32 UTC by ldai1

**Issue #:**

**Description of changes:**
Add some instructions for CSP setup

**Testing**

1. Have you successfully run `npm run build:release` locally? Yes
2. How did you test these changes? N/A
3. Can these changes be tested using the demo application? If yes, which demo application can be used to test it? N/A
4. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved? N/A
5. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved? N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-01 19:06 UTC, michhyun1 commented
Is it possible to add that SecurityPolicyViolationEvent handler to log any errors with that CSP policies?

2021-09-10 17:05 UTC, richnew10 requested changes

2021-09-10 17:05 UTC, richnew10 commented on src/signalingclient/DefaultSignalingClient.ts
> +    /* istanbul ignore next */
This means you haven't written tests for this. Please do!

2021-09-10 17:05 UTC, richnew10 commented on src/signalingclient/DefaultSignalingClient.ts
> +  private listenForCSPViolations(): void {
Consider also using a closure to track whether the listener has been installed, so we only do it once.

2021-09-10 17:05 UTC, richnew10 commented on src/signalingclient/DefaultSignalingClient.ts
> +    document.addEventListener('securitypolicyviolation', (e: SecurityPolicyViolationEvent) => {
How does a customer turn this off?

2021-09-10 17:09 UTC, richnew10 commented
Overall comment:

* If a customer just adds `connect-src`, does their app work?
* Have you tested this theory with a deployment of the demo app?

2021-09-14 19:03 UTC, tenge-amzn requested changes

2021-09-14 19:03 UTC, tenge-amzn commented on guides/14_Content_Security_Policy.md
> +Modern web applications use [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to protect users from certain classes of attacks. Adding a security policy by configuring
>Modern web applications use Content Security Policy

Is this a quote from somewhere?

2021-09-14 19:07 UTC, richnew10 commented on guides/14_Content_Security_Policy.md
> +Modern web applications use [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to protect users from certain classes of attacks. Adding a security policy by configuring
I wrote that sentence in particular.

2021-09-15 12:53 UTC, ldai1 commented on CHANGELOG.md
> +- Add new documentation page for Content Security Policy setup guide.
Fixed

2021-09-15 13:23 UTC, ldai1 commented on CHANGELOG.md
> +- Add `securitypolicyviolation` event listener to listen for CSP violations.
Fixed

2021-09-15 13:30 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +Modern web applications use [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to protect users from certain classes of attacks. Adding a security policy by configuring
Fixed

2021-09-23 23:13 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +Content-Security-Policy: connect-src 'self' '*.amazonaws.com';
No, that means if customers enable csp, they need to  include a connect-src source for '*.amazonaws.com'", otherwise it is not required.

2021-09-23 23:17 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +Chime JS SDK manages websocket connections for clients to receive real time updates on messages and events. For more information about permission setup and establishing a websocket connection, see [U
Fixed.

2021-09-23 23:17 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +```
I will delete this part and roll this up into "Meetings connectivity"

2021-09-23 23:23 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +The JS SDK listen to securitypolicyviolation events and log blocked URI during signaling connection for join meetings. An error code starting with "Security Policy Violation" if there is securitypoli
Fixed.

2021-09-23 23:32 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +If you need guidance with correct CSP configuration to use Amazon Voice Focus, contact AWS Support.
Fixed.

2021-09-23 23:34 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +Given the above CSP header, other connections that are not with `*.chime.aws` suffix will be blocked and won't load.
Fixed.

2021-09-23 23:34 UTC, ldai1 commented on guides/14_Content_Security_Policy.md
> +To add web sockets to the security policy for security contraints, you can add the web socket protocol (ws:) to the connect-src directive.
Fixed.

2021-09-24 20:40 UTC, richnew10 commented
Please rebase on top of `master`.

2021-09-24 21:09 UTC, closed without merging

2021-09-24 21:13 UTC, tenge-amzn commented
I'm a bit confused on what happened on this PR? It seems merged but I don't see it in the master branch? Is there a "force-push" action? That's kinda a dangerous thing to do.

2021-09-24 23:16 UTC, richnew10 commented
This branch got set to [a previous HEAD](https://github.com/aws/amazon-chime-sdk-js/commit/acfa5efba98209fccebc2971901d936dbcfafd84), so GitHub thinks it was already deployed. Force-pushing to `csp` would actually be the correct way to fix that rebase, but instead we're off in #1620.