Removed upward logic in VideoPriorityBasedPolicyConfig
aws/amazon-chime-sdk-js pull request #2032
Opened 2022-02-17 08:57 UTC by bjason

**Issue #:**

The content share may fail to resume after turning off network link conditioner. 

**Description of changes:**

Removed upward logic in `VideoPriorityBasedPolicyConfig`.

**Testing:**

Smoke tested locally. Used network link conditioner to control bandwidth to validate video tile will resume after bandwidth recovers.

*Can these tested using a demo application? Please provide reproducible step-by-step instructions.*

no

**Checklist:**

1. Have you successfully run `npm run build:release` locally?
yes

2. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?
no

3. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?
no

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-17 19:52 UTC, ltrung commented
@bjason Can we put more details on the PR description about the issue? Why we want to remove the upward logic (maybe explain what that is also)? Otherwise, noone would understand why we do this several months from now.

2022-02-18 23:17 UTC, hensmi-amazon submitted a review, later dismissed
For context, this was causing issues to recovery time, and its initial focus was towards slowing downturns in BWE when the network is actually stable anyways. We may come back to configuring the recovery delay another time.

2022-02-21 16:41 UTC, vidya-mohan requested changes
Can you update the changelog with more details on the fix - right now its notclear what the fix is doing

2022-02-21 16:50 UTC, hensmi-amazon approved these changes

2022-02-21 16:57 UTC, vidya-mohan approved these changes

2022-02-21 17:42 UTC, merged