Separated mobile metrics from browser metrics
aws/amazon-chime-sdk-js pull request #2075
Opened 2022-02-28 23:13 UTC by LeviSklaroff

**Issue #:**

**Description of changes:**

**Testing:**

*Can these tested using a demo application? Please provide reproducible step-by-step instructions.*

**Checklist:**

1. Have you successfully run `npm run build:release` locally?

2. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?

3. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-28 23:13 UTC, devalevenkatesh submitted a review, later dismissed

2022-02-28 23:18 UTC, ltrung approved these changes

2022-03-01 00:10 UTC, simmkyu requested changes

2022-03-01 00:10 UTC, simmkyu commented on integration/js/utils/SdkBaseTest.js
> +    if(kiteConfig.capabilities.platform == 'IOS' || kiteConfig.capabilities.platform == 'ANDROID') {
nit
- Use `===`
- `if(` => `if ( `

2022-03-01 00:10 UTC, simmkyu commented on integration/js/utils/SdkBaseTest.js
> +      this.testName = 'Mobile_'+testName;
nit: `'+testName` => `' + testName`

2022-03-01 00:10 UTC, simmkyu commented on integration/js/utils/SdkBaseTest.js
> +    }
`} else {`

2022-03-01 00:22 UTC, LeviSklaroff commented on integration/js/utils/SdkBaseTest.js
> +    if(kiteConfig.capabilities.platform == 'IOS' || kiteConfig.capabilities.platform == 'ANDROID') {
Updated, will make change on 3x to.

2022-03-01 17:56 UTC, simmkyu approved these changes

2022-03-01 17:57 UTC, merged