Add data message throttle limit in API documentation
aws/amazon-chime-sdk-js pull request #759
Opened 2020-10-06 16:53 UTC by anuranduttaroy

**Issue #:** https://github.com/aws/amazon-chime-sdk-js/issues/754

**Description of changes:**
Add data message throttle limit in API documentation

**Testing**

1. Have you successfully run `npm run build:release` locally?
Yes.

2. How did you test these changes?
Documentation update.

3. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?
NA

4. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?
NA

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-06 16:56 UTC, ltrung commented on src/datamessage/DataMessage.ts
> +   * Throttling limits: Rate:100 Burst:200
Should we document this in code like this or should it go to README or FAQs?

2020-10-06 16:58 UTC, ltrung requested changes
Should we document this in code like this or should it go to README or FAQs?

2020-10-06 22:09 UTC, simmkyu commented on guides/03_API_Overview.md
> +If you send too many messages at once, your messages may be returned to you with the [throttled](https://aws.github.io/amazon-chime-sdk-js/classes/datamessage.html#throttled) flag set. The current th
`soft limits ... is` => `soft limit ... is` ?

2020-10-06 22:20 UTC, simmkyu approved these changes

2020-10-07 00:31 UTC, ltrung approved these changes

2020-10-07 00:32 UTC, merged